### ISSUE TITLE
npm install 出错了

### ISSUE THREAD

**Issue by rxdff** [ikimiler/react-native-video-project#1]
初学RN,npm install发生异常，该怎么解决
![image](https://user-images.githubusercontent.com/11887217/53155101-53c31980-35f7-11e9-82b7-b701eed79761.png)
![image](https://user-images.githubusercontent.com/11887217/53155156-69384380-35f7-11e9-9a17-5779e852b6f6.png)

**Comment by ikimiler** [comment]
npm 是否安装正常？先在一个空文件夹下执行npm init 看是否正确

**Comment by rxdff** [comment]
> npm 是否安装正常？先在一个空文件夹下执行npm init 看是否正确

npm init是正常的  空文件夹下创建了package.json

**Comment by ikimiler** [comment]
你的qq多少，我加下你

**Comment by ikimiler** [comment]
你先用npm install -g react-native-cli 然后在项目目录下 npm install 看是否解决

**Comment by rxdff** [comment]
> 你的qq多少，我加下你

1415212259
