### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by aichangqing** [ikimiler/react-native-video-project#10]
编译出错
Could not find method register() for arguments [forwardDebugPort, class org.gradle.api.tasks.Exec, build_7oyalcyumyz7bb78lvycvtkae$_run_closure2@147833f8] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

请问这是什么问题？

**Comment by ikimiler** [comment]
先用as构建一下安卓项目看能不能成功，成功了再react-native run-android

**Comment by x2201783** [comment]
我也是这个问题， 就是as运行报错
