### ISSUE TITLE
微信群进不去了

### ISSUE THREAD

**Issue by He-WenJie** [ikimiler/react-native-video-project#11]
微信群进不去了

**Comment by ikimiler** [comment]
加我好友 我拉你 vx:andmizi

**Comment by CrazyMan2** [comment]
> 加我好友我拉你vx：andmizi

该用户不存在

**Comment by ikimiler** [comment]
新版微信支持修改微信号，我给改成了tencent_kimi🤣

**Comment by mirceaciu** [comment]
I don't know anyone who uses WeChat, can any of you give me an invite?

**Comment by ikimiler** [comment]
> I don't know anyone who uses WeChat, can any of you give me an invite?

wechat:inskimi
