### ISSUE TITLE
如何解析本地的m3u8

### ISSUE THREAD

**Issue by LostLord** [ikimiler/react-native-video-project#12]
开发过程发现缓存本地的m3u8无法播放，请问是如何播放本地的m3u8文件的，用本地代理可以正常播放，但是用file://无法播放，请问这个是怎样实现本地播放的

**Comment by ikimiler** [comment]
此项目里用的就是file://本地路径去播放的，你可以看下具体的详细错误日志，是路径没有解析出来还是m3u8文件格式的问题？

**Comment by LostLord** [comment]
有一个解决方法，就是开启本地代理，利用http://localhost:8888/demo.m3u8，这种可以正常播放

**Comment by ikimiler** [comment]
你这也是属于远程播放了
