### ISSUE TITLE
不能看

### ISSUE THREAD

**Issue by Yunnathai** [ikimiler/react-native-video-project#2]
视频也不能下载。。下载100%  就提示资源错误 重试

而且只能下载一集，不能再加入。。。
确定是线上用的么~~~

设备安卓~

**Comment by ikimiler** [comment]
是的，只是移除了数据层，目前数据源只配置了一个静态视频，在data.json里可以查看并更改。
至于，下载100%提示资源错误，你方便看下log并提交上来，netlog-过滤下日志

**Comment by Yunnathai** [comment]
哦  明白了。
请问下两个问题想请教下  
1.下载的话支持下载的个数控制么？以及后台下载。如果有多个任务，其中一个任务完成后会自动下载下一个任务么？这时候可能已经离开了下载页面 甚至置为后台运行。
2.m3u8 下载下来后都是ts文件 react-native-video 怎么进行播放呢~？不需要合并ts文件么。

**Comment by ikimiler** [comment]
1:暂不支持下载个数控制，程序是一个下载任务对应一个线程，最大线程数也没做处理。暂不支持后台下载，下载页面有提示到：下载过程中请保持app为打开状态。
2:m3u8文件会逐个去下载对应的ts文件，最终会合并本地的ts文件到一个新的m3u8中，播放的话直接播放本地的m3u8就可以了

**Comment by Yunnathai** [comment]
这个怎么去合并的呢

**Comment by ikimiler** [comment]
不需要亲自合并，只需要把m3u8文件里的ts路径替换为本地的ts文件就可以了，具体的你跟一下download下载的js代码
