### ISSUE TITLE
npm install 报错啊

### ISSUE THREAD

**Issue by ghost** [ikimiler/react-native-video-project#5]
![Snipaste_2019-05-06_01-17-07](https://user-images.githubusercontent.com/48319403/57197662-af693600-6f9c-11e9-957f-a660947826eb.png)

**Comment by ikimiler** [comment]
react native cli 安装了吗

**Comment by ghost** [comment]
装了啊

**Comment by ikimiler** [comment]
你先初始化一个新项目看是环境是否正常

**Comment by ikimiler** [comment]
该 issue 被关闭了，如果还有疑问，请联系我qq329629722
