### ISSUE TITLE
ld: library not found for -lRealmReact  ios编译报错

### ISSUE THREAD

**Issue by allencelee** [ikimiler/react-native-video-project#9]
** BUILD FAILED **

The following build commands failed:

	Ld /Users/lee/Desktop/react-native-video-project-master/ios/build/Build/Products/Debug-iphonesimulator/colavideoapp.app/colavideoapp normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/colavideoapp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/colavideoapp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/colavideoapp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:15)
    at /Users/lee/Desktop/react-native-video-project-master/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5

**Comment by ikimiler** [comment]
https://blog.csdn.net/ayru60/article/details/74518992  看下这个文章
